// Code generated by "stringer -type Hook ../hook.go"; DO NOT EDIT

package torsten

import "fmt"

const _Hook_name = "PreCreatePostCreatePreRemovePostRemovePreListPostListPreGetPostGet"

var _Hook_index = [...]uint8{0, 9, 19, 28, 38, 45, 53, 59, 66}

func (i Hook) String() string {
	i -= 1
	if i < 0 || i >= Hook(len(_Hook_index)-1) {
		return fmt.Sprintf("Hook(%d)", i+1)
	}
	return _Hook_name[_Hook_index[i]:_Hook_index[i+1]]
}
